#!/bin/sh

request_handle()
{
	. $(dirname $0)/get_path
	local init_file="$(get_path)/init.status"
	local config_file="$(get_path)/PhMain.ini"
	
	if [ -f $init_file ]; then
		rm $init_file >/dev/null 2>&1
	fi	
	if [ -f $config_file ]; then
		rm $config_file >/dev/null 2>&1
	fi
	echo "result_code:0"

	{
		sleep 5 >/dev/null 2>&1
		/etc/init.d/oray_phddns reload >/dev/null 2>&1 &
	} &
	
	return 0
}

case $1 in
	request_handle)
		request_handle "$2"
		;;
	*)
		;;
esac
